
Inputs:
  - SiemensCPU: siemens.snap7_connect
    enabled: False
    host: "<S7 PLC IP>"

  - SiemensServer: siemens.snap7_server
    enabled: False
    port: 102

  - Balluff: balluff.balluff_html
    enabled: False

  - AllenBradleyCPU: rockwell.allen_bradley_connect
    enabled: False
    host: "<AB PLC IP>"
  
  - Input: dummy
    message: Hello World!

  - Replay: replay_influxdb
    enabled: False
    url: "http://influxdb:8086"
    token: "<token>"
    org: "myorg"
    bucket: "energy-monitor"
    start_time: 01.01.2000 01:00:00

Middlewares:
  - Warning: debug
    enabled: False
    enable_output: False
  - TimeCorrelation: time_correlation
    submodules:
    - MatchAny: filters
      series: plant
      enable_output: False
      table_move_up: 1
    - ComplexFilter: filters
      predicate: "measurement_480v and measurement_24v and avg(measurement_24v.current) > 0.6"
      submodules:
      - ComplexSelector: selectors
        selector: "avg(measurement_480v.current)"
        enable_output: False
    - Aggregate: aggregators
      series: 24v
      timespan: 0.1
      avg:
      - voltage
      min:
      - status
      - overload
      submodules:
      - PrintStats: debug
        enable_output: True



Outputs:
  - CSVStorage: csv_file
    path: dummy-logs
    enabled: True
  - JSONOutput: stdout
    enabled: False

Logging:
  version: 1
  formatters:
    standard:
      #format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
      format: "[%(levelname)s] %(name)s: %(message)s"
  handlers:
    default:
      level: INFO
      formatter: standard
      class: logging.StreamHandler
      stream: ext://sys.stderr
  loggers:
    '':
      handlers:
      - default
      level: DEBUG
      propagate: false
    inputs.rockwell.allen_bradley_connect:
      handlers:
      - default
      level: WARNING
      propagate: false
    snap7.server:
      handlers:
      - default
      level: WARNING
      propagate: false
    __main__:
      handlers:
      - default
      level: DEBUG
      propagate: false